# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xocr.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'xocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xpertagent.protos import xcommon_pb2 as xcommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nxocr.proto\x12\x11xpertagent.protos\x1a\rxcommon.proto\"\x1d\n\nOCRRequest\x12\x0f\n\x07img_url\x18\x01 \x01(\t\"H\n\x0bOCRResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.xpertagent.protos.Status\x12\x0e\n\x06result\x18\x02 \x01(\t2^\n\x0bXOCRService\x12O\n\x0cProcessImage\x12\x1d.xpertagent.protos.OCRRequest\x1a\x1e.xpertagent.protos.OCRResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=48
  _globals['_OCRREQUEST']._serialized_end=77
  _globals['_OCRRESPONSE']._serialized_start=79
  _globals['_OCRRESPONSE']._serialized_end=151
  _globals['_XOCRSERVICE']._serialized_start=153
  _globals['_XOCRSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
